version: '3'
    
services:
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=capstone3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=10tujuh1
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres